{
 "title": "Storj V3 Health",
 "description": "Keeping a close eye on all valuable metrics to be a successful SNO",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"StorJHealth\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Host Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Reboots",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Reboots" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "PUT Limiter",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTLimit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Drive H: Free",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Free_Megabytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "H:" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "kalev-PC" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$hostname: $col",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Priviledged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "kalev-PC" }
     ]
    }
   ]
  },
  {
   "title": "Audit Crit",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedCrit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Audit Warn",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedWarn" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "InfoDB check",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "InfoDBcheck" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "24hr Trending Health Diff",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "PUT Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Accepted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTAcceptRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Audit Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Ratio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Repair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Repair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairRatio" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "24hr Count Diff - Failed/Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Deleted",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTFailed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLFailed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GET Repair Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairFail" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Repair Failed",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairFailed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "GET Ratio",
   "type": "grafana-piechart-panel",
   "description": "Downloads from this node - (uploads to client)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "DL Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLFailed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "DL Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "DLSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUT Ratio",
   "type": "grafana-piechart-panel",
   "description": "Downloads to this node (uploads from client)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "PUT Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTFailed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUT Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Concurrency Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTLimit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Audit Crit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedCrit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "Audit Warn",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedWarn" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Audit Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Success" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GET Repair",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "GETRepair Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "GETRepair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "GETRepairSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "PUT Repair",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "PUTRepair Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairFailed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    },
    {
     "alias": "PUTRepair Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "PUTRepairSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "Container uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HOST$/" }
     ]
    }
   ]
  },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Received Bytes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "instance",
       "operator": "=",
       "value": "Realtek PCIe GBE Family Controller"
      }
     ]
    },
    {
     "alias": "Sent Bytes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "instance",
       "operator": "=",
       "value": "Realtek PCIe GBE Family Controller"
      }
     ]
    }
   ]
  },
  {
   "title": "Wallet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "BalanceSTORJ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wallet val.",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$",
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "BalanceUSD" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storj internal dashbord info",
   "type": "graph",
   "description": "queried over sroagenode dashboard API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Bandwith used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "bandwith_used_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Disk Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "disk_used_gb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "directory_size_kilobytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reboot Alert",
   "type": "graph",
   "description": "Alerts if reboots >1 in $timeframe",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Reboots",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "Reboots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Audit Crit",
   "type": "graph",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "FailedCrit" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "InfoDB check",
   "type": "graph",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJHealth",
     "select": [
      [
       { "params": [ "InfoDBcheck" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "STORJ Price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "alias": "€",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "STORJPriceEUR" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StorJToken",
     "select": [
      [
       { "params": [ "STORJPriceUSD" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true
  }
 ]
}